# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import profileme.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.FileField(blank=True, help_text='200x200px', max_length=120, null=True, upload_to='images/photo/%Y/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=profileme.models.get_cv_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(blank=True, choices=[('c', 'contract'), ('p', 'permanent')], max_length=1, null=True, verbose_name='Job type'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, help_text='200x200px', max_length=120, null=True, upload_to='images/photo/%Y/', verbose_name='Photo'),
        ),
    ]
