# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileme', '0002_auto_20170517_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='companies.Company', verbose_name='Company'),
        ),
    ]
