# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_to', models.EmailField(max_length=254, verbose_name='Email of recipient')),
                ('invite_key', models.CharField(max_length=30, unique=True, verbose_name='Invitation key')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(editable=False)),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted by receiver?')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo size 600x200px, .jpg, .png, .gif formats', null=True, upload_to='images/company/logo/%Y'),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruit.Company'),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='sent_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
