# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='users.Agent', verbose_name='Posted By'),
        ),
    ]
