# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileme', '0003_auto_20170517_1612'),
        ('recruit', '0002_auto_20170517_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='sent_to_user',
        ),
        migrations.RemoveField(
            model_name='companyrequestinvitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyrequestinvitation',
            name='user',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyInvitation',
        ),
        migrations.DeleteModel(
            name='CompanyRequestInvitation',
        ),
    ]
