# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:53
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20170520_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
    ]
