# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20170427_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='accepted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
