# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20170427_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=200, unique=True, verbose_name='Domain name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address_1',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Address line 1'),
        ),
    ]
