# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruit', '0004_auto_20170509_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequestInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='Request Invitation key')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_request', to='recruit.Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
