# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_connectioninvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectioninvite',
            options={'verbose_name': 'Connection Invitation', 'verbose_name_plural': 'Connection Invitations'},
        ),
        migrations.RemoveField(
            model_name='connectioninvite',
            name='connectee',
        ),
        migrations.AddField(
            model_name='connectioninvite',
            name='connectee_email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='Connectee'),
            preserve_default=False,
        ),
    ]
