# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_auto_20170516_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
