# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_company_allow_auto_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrequestinvitation',
            name='key',
        ),
        migrations.AddField(
            model_name='companyrequestinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Request Invitation key'),
        ),
    ]
