# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20170529_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninvite',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='uuid',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
