# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:57
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='residence_country',
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
