# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20170522_0603'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='City', max_length=200, verbose_name='City'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='recruit.Skill', verbose_name='Skills'),
        ),
    ]
