# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_auto_20170608_1243'),
        ('users', '0011_remove_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
                ('experience', models.SmallIntegerField(verbose_name='Years of Experience')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_skills', to='users.Candidate', verbose_name='Candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='recruit.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Candidate Skill',
                'verbose_name_plural': 'Candidate Skills',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', through='users.CandidateSkill', to='recruit.Skill', verbose_name='Skills'),
        ),
    ]
