from django.utils.translation import ugettext_lazy as _

# yes, these are countries )
COUNTRIES = (
    ('gb', _('United Kingdom')),
    ('af', _('Afghanistan')),
    ('ax', _('Aland Islands')),
    ('al', _('Albania')),
    ('dz', _('Algeria')),
    ('as', _('American Samoa')),
    ('ad', _('Andorra')),
    ('ao', _('Angola')),
    ('ai', _('Anguilla')),
    ('aq', _('Antarctica')),
    ('ag', _('Antigua and Barbuda')),
    ('ar', _('Argentina')),
    ('am', _('Armenia')),
    ('aw', _('Aruba')),
    ('au', _('Australia')),
    ('at', _('Austria')),
    ('az', _('Azerbaijan')),
    ('bs', _('Bahamas')),
    ('bh', _('Bahrain')),
    ('bd', _('Bangladesh')),
    ('bb', _('Barbados')),
    ('by', _('Belarus')),
    ('be', _('Belgium')),
    ('bz', _('Belize')),
    ('bj', _('Benin')),
    ('bm', _('Bermuda')),
    ('bt', _('Bhutan')),
    ('bo', _('Bolivia')),
    ('ba', _('Bosnia and Herzegovina')),
    ('bw', _('Botswana')),
    ('bv', _('Bouvet Island')),
    ('br', _('Brazil')),
    ('io', _('British Indian Ocean Territory')),
    ('bn', _('Brunei Darussalam')),
    ('bg', _('Bulgaria')),
    ('bf', _('Burkina Faso')),
    ('bi', _('Burundi')),
    ('kh', _('Cambodia')),
    ('cm', _('Cameroon')),
    ('ca', _('Canada')),
    ('cv', _('Cape Verde')),
    ('ky', _('Cayman Islands')),
    ('cf', _('Central African Republic')),
    ('td', _('Chad')),
    ('cl', _('Chile')),
    ('cn', _('China')),
    ('cx', _('Christmas Island')),
    ('cc', _('Cocos (Keeling) Islands')),
    ('co', _('Colombia')),
    ('km', _('Comoros')),
    ('cg', _('Congo')),
    ('cd', _('Congo, The Democratic Republic of the')),
    ('ck', _('Cook Islands')),
    ('cr', _('Costa Rica')),
    ('ci', _('Cote d\'Ivoire')),
    ('hr', _('Croatia')),
    ('cu', _('Cuba')),
    ('cy', _('Cyprus')),
    ('cz', _('Czech Republic')),
    ('dk', _('Denmark')),
    ('dj', _('Djibouti')),
    ('dm', _('Dominica')),
    ('do', _('Dominican Republic')),
    ('ec', _('Ecuador')),
    ('eg', _('Egypt')),
    ('sv', _('El Salvador')),
    ('gq', _('Equatorial Guinea')),
    ('er', _('Eritrea')),
    ('ee', _('Estonia')),
    ('et', _('Ethiopia')),
    ('fk', _('Falkland Islands (Malvinas)')),
    ('fo', _('Faroe Islands')),
    ('fj', _('Fiji')),
    ('fi', _('Finland')),
    ('fr', _('France')),
    ('gf', _('French Guiana')),
    ('pf', _('French Polynesia')),
    ('tf', _('French Southern Territories')),
    ('ga', _('Gabon')),
    ('gm', _('Gambia')),
    ('ge', _('Georgia')),
    ('de', _('Germany')),
    ('gh', _('Ghana')),
    ('gi', _('Gibraltar')),
    ('gr', _('Greece')),
    ('gl', _('Greenland')),
    ('gd', _('Grenada')),
    ('gp', _('Guadeloupe')),
    ('gu', _('Guam')),
    ('gt', _('Guatemala')),
    ('gg', _('Guernsey')),
    ('gn', _('Guinea')),
    ('gw', _('Guinea-Bissau')),
    ('gy', _('Guyana')),
    ('ht', _('Haiti')),
    ('hm', _('Heard Island and McDonald Islands')),
    ('va', _('Holy See (Vatican City State)')),
    ('hn', _('Honduras')),
    ('hk', _('Hong Kong')),
    ('hu', _('Hungary')),
    ('is', _('Iceland')),
    ('in', _('India')),
    ('id', _('Indonesia')),
    ('ir', _('Iran, Islamic Republic of')),
    ('iq', _('Iraq')),
    ('ie', _('Ireland')),
    ('im', _('Isle of Man')),
    ('il', _('Israel')),
    ('it', _('Italy')),
    ('jm', _('Jamaica')),
    ('jp', _('Japan')),
    ('je', _('Jersey')),
    ('jo', _('Jordan')),
    ('kz', _('Kazakhstan')),
    ('ke', _('Kenya')),
    ('ki', _('Kiribati')),
    ('kp', _('Korea, Democratic People\'s Republic of')),
    ('kr', _('Korea, Republic of')),
    ('kw', _('Kuwait')),
    ('kg', _('Kyrgyzstan')),
    ('la', _('Lao People\'s Democratic Republic')),
    ('lv', _('Latvia')),
    ('lb', _('Lebanon')),
    ('ls', _('Lesotho')),
    ('lr', _('Liberia')),
    ('ly', _('Libyan Arab Jamahiriya')),
    ('li', _('Liechtenstein')),
    ('lt', _('Lithuania')),
    ('lu', _('Luxembourg')),
    ('mo', _('Macao')),
    ('mk', _('Macedonia, The Former Yugoslav Republic of')),
    ('mg', _('Madagascar')),
    ('mw', _('Malawi')),
    ('my', _('Malaysia')),
    ('mv', _('Maldives')),
    ('ml', _('Mali')),
    ('mt', _('Malta')),
    ('mh', _('Marshall Islands')),
    ('mq', _('Martinique')),
    ('mr', _('Mauritania')),
    ('mu', _('Mauritius')),
    ('yt', _('Mayotte')),
    ('mx', _('Mexico')),
    ('fm', _('Micronesia, Federated States of')),
    ('md', _('Moldova')),
    ('mc', _('Monaco')),
    ('mn', _('Mongolia')),
    ('me', _('Montenegro')),
    ('ms', _('Montserrat')),
    ('ma', _('Morocco')),
    ('mz', _('Mozambique')),
    ('mm', _('Myanmar')),
    ('na', _('Namibia')),
    ('nr', _('Nauru')),
    ('np', _('Nepal')),
    ('nl', _('Netherlands')),
    ('an', _('Netherlands Antilles')),
    ('nc', _('New Caledonia')),
    ('nz', _('New Zealand')),
    ('ni', _('Nicaragua')),
    ('ne', _('Niger')),
    ('ng', _('Nigeria')),
    ('nu', _('Niue')),
    ('nf', _('Norfolk Island')),
    ('mp', _('Northern Mariana Islands')),
    ('no', _('Norway')),
    ('om', _('Oman')),
    ('pk', _('Pakistan')),
    ('pw', _('Palau')),
    ('ps', _('Palestinian Territory, Occupied')),
    ('pa', _('Panama')),
    ('pg', _('Papua New Guinea')),
    ('py', _('Paraguay')),
    ('pe', _('Peru')),
    ('ph', _('Philippines')),
    ('pn', _('Pitcairn')),
    ('pl', _('Poland')),
    ('pt', _('Portugal')),
    ('pr', _('Puerto Rico')),
    ('qa', _('Qatar')),
    ('re', _('Reunion')),
    ('ro', _('Romania')),
    ('ru', _('Russian Federation')),
    ('rw', _('Rwanda')),
    ('bl', _('Saint Barthelemy')),
    ('sh', _('Saint Helena')),
    ('kn', _('Saint Kitts and Nevis')),
    ('lc', _('Saint Lucia')),
    ('mf', _('Saint Martin')),
    ('pm', _('Saint Pierre and Miquelon')),
    ('vc', _('Saint Vincent and the Grenadines')),
    ('ws', _('Samoa')),
    ('sm', _('San Marino')),
    ('st', _('Sao Tome and Principe')),
    ('sa', _('Saudi Arabia')),
    ('sn', _('Senegal')),
    ('rs', _('Serbia')),
    ('sc', _('Seychelles')),
    ('sl', _('Sierra Leone')),
    ('sg', _('Singapore')),
    ('sk', _('Slovakia')),
    ('si', _('Slovenia')),
    ('sb', _('Solomon Islands')),
    ('so', _('Somalia')),
    ('za', _('South Africa')),
    ('gs', _('South Georgia and the South Sandwich Islands')),
    ('es', _('Spain')),
    ('lk', _('Sri Lanka')),
    ('sd', _('Sudan')),
    ('sr', _('Suriname')),
    ('sj', _('Svalbard and Jan Mayen')),
    ('sz', _('Swaziland')),
    ('se', _('Sweden')),
    ('ch', _('Switzerland')),
    ('sy', _('Syrian Arab Republic')),
    ('tw', _('Taiwan, Province of China')),
    ('tj', _('Tajikistan')),
    ('tz', _('Tanzania, United Republic of')),
    ('th', _('Thailand')),
    ('tl', _('Timor-Leste')),
    ('tg', _('Togo')),
    ('tk', _('Tokelau')),
    ('to', _('Tonga')),
    ('tt', _('Trinidad and Tobago')),
    ('tn', _('Tunisia')),
    ('tr', _('Turkey')),
    ('tm', _('Turkmenistan')),
    ('tc', _('Turks and Caicos Islands')),
    ('tv', _('Tuvalu')),
    ('ug', _('Uganda')),
    ('ua', _('Ukraine')),
    ('ae', _('United Arab Emirates')),
    ('us', _('United States')),
    ('um', _('United States Minor Outlying Islands')),
    ('uy', _('Uruguay')),
    ('uz', _('Uzbekistan')),
    ('vu', _('Vanuatu')),
    ('ve', _('Venezuela')),
    ('vn', _('Viet Nam')),
    ('vg', _('Virgin Islands, British')),
    ('vi', _('Virgin Islands, U.S.')),
    ('wf', _('Wallis and Futuna')),
    ('eh', _('Western Sahara')),
    ('ye', _('Yemen')),
    ('zm', _('Zambia')),
    ('zw', _('Zimbabwe')),
)
